# Generated by Django 4.2.1 on 2023-05-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('brand_image', models.ImageField(default='No image available', upload_to='photos/brand')),
                ('brand_address', models.TextField(max_length=200)),
                ('brand_description', models.TextField(max_length=300)),
            ],
        ),
    ]
