# Generated by Django 4.2.1 on 2023-05-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram_variant',
            field=models.ManyToManyField(blank=True, to='store.ramvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screensize_variant',
            field=models.ManyToManyField(blank=True, to='store.screensizevariant'),
        ),
    ]
