# Generated by Django 4.2.1 on 2023-05-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_filter_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filter_price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.price_filter'),
        ),
    ]
