# Generated by Django 4.2.1 on 2023-05-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_filter_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='filter_price',
            new_name='filt_price',
        ),
    ]
