# Generated by Django 4.2.1 on 2023-05-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_filter_price_product_filt_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filt_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.price_filter'),
        ),
    ]
