# Generated by Django 4.2.1 on 2023-06-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_price_filter_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filt_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.price_filter'),
        ),
    ]
