# Generated by Django 4.2.1 on 2023-06-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='screensize_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='screensize_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.screensizevariant'),
        ),
    ]
