# Generated by Django 4.2.1 on 2023-06-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_screensize_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='screensize_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='screensize_variant',
            field=models.ManyToManyField(blank=True, to='store.screensizevariant'),
        ),
    ]
