# Generated by Django 4.2.1 on 2023-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='offer',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
