# Generated by Django 4.2.1 on 2023-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='landmark',
        ),
        migrations.AddField(
            model_name='user_address',
            name='address',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
