# Generated by Django 4.2.1 on 2023-05-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
