# Generated by Django 4.2.1 on 2023-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
