"""
Django settings for lapkart project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from django.contrib.messages import constants as messages


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^-*z-s)jp6efs&d4*@nckgtfkmw0+mur80p@ctw5=qqpds-47e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'useraccount.Account'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'useraccount',
    'category',
    'store',
    'cart',
    'dashboard_home',
    'dashboard',
    'dashboard_users',
    'userprofile',
    'wishlist',
    'checkout',
    'order',
    'admin_product',
    'admin_banner',
    'admin_order',
    'admin_offer',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lapkart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_counter',
                'wishlist.context_processors.wishlist_counter'
            ],
        },
    },
]

WSGI_APPLICATION = 'lapkart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'lapkart',
        'USER' : 'postgres',
        'PASSWORD' : 'achumol',
        'HOST' : 'localhost',
        'POST' : '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# RAZORPAY_KEY_ID = 'rzp_test_S2UWlLJOKSkZv5'
# RAZORPAY_KEY_SECRET = 'bBGeDgA13zIbso54fEIla6sW'

#===================Sending Email===============

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'sahlavalillath@gmail.com'
EMAIL_HOST_PASSWORD = 'whwvdtahfqmgbxmv'
EMAIL_USE_TLS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR / 'static')
]

MEDIA_URL = '/uploads/'
MEDIA_ROOT = BASE_DIR / 'uploads/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#===================RAZORPAY GATEWAY==========

KEY = 'rzp_test_IAsoLLg94jUgWM'
SECRET = 'l67awLFoLavydlJ3bM23cvtU'



#=============TWILIO============


# ACCOUNT_SID = 'ACd611fb0170869167d1b0ad481f26b296'
# AUTH_TOKEN = '29df5bb76a4afadd0452b1ae9d448677'